# Generated by Django 5.0.3 on 2024-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
