# Generated by Django 5.0.3 on 2024-04-14 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_catgory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory',
            name='sub_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catgory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.catgory'),
        ),
        migrations.AlterField(
            model_name='catgory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='home.catgory'),
        ),
    ]
