# Generated by Django 5.0.3 on 2024-04-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_catgory_sub_cat_catgory_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='home.catgory'),
        ),
    ]
